### ISSUE TITLE
Compatibility between standard wifi and linuxesp ?

### ISSUE THREAD

**Issue by joelcollet** [thomasfla/Linux-ESPNOW#8]
Hi

i'am very interested in this linux esp code for driving equatorial mount for astronomy.
However i have a question:
Can this protocol be used on the same wifi card than the one used for standard network (i mean having the wifi connected to an access point AND communicate with esp device too) or should it be a dedicated card for only espnow?

Regards
Joël

**Comment by thomasfla** [comment]
Hi, 

You would need to dedicate a Wi-Fi interface to the espnow in monitor mode, I don't see an easy way to use the same interface for both, unfortunately.

Best,
T.

**Comment by joelcollet** [comment]
Hi Thomas

Ok, thanks for the info.
Regards
Joël
